services:
  - type: web
    name: cadastro-produtos-clientes-api
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: uvicorn src.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
